
export const PRODUCT = [
    {
        id: '1',
        name: "De'Longhi An array of strings – used when value and label are the same",
        rating: 5,
        price: '100$',
        prevPrice: '134$',
        percent: '22%',
        imgUrl: 'https://stockmann.ru/istk/wo6RkrxfoLEKPLsSn08y9eC1wwKD65s6uvpT9a4tqYY/rs:fill:708:1119:0/g:no/bG9jYWw6Ly8vdXBsb2FkLy9jbXMvc3RhdGljL2RhdGFfcGljdHVyZXMvRk9WbDNkQWxXMjlYejBhWlcxTTdZV1RrNkd0V1RIZVVZRnlhajVPYS5wbmc.jpg',
        isNew: false,
        isGoodPrice: true,
    },
    {
        id: '2',
        name: 'HyperX Alloy Origins An array of strings – used when value and label are the same',
        rating: 3,
        price: '12$',
        prevPrice: '34$',
        percent: '20%',
        imgUrl: 'https://m.media-amazon.com/images/I/61+Jg1fJSsL._AC_UL320_.jpg',
        isNew: true,
        isGoodPrice: false,
    },

    {
        id: '3',
        name: '4 Tier Plastic Storage An array of strings – used when value and label are the same',
        rating: 5,
        price: '40$',
        prevPrice: '60$',
        percent: '10%',
        imgUrl: 'https://m.media-amazon.com/images/I/71Snbx6a0hL._AC_UL320_.jpg',
        isNew: true,
        isGoodPrice: true,
    },
    {
        id: '4',
        name: 'Melissa & Doug',
        rating: 2,
        price: '40$',
        prevPrice: '60$',
        percent: '20%',
        imgUrl: 'https://m.pm.ru/global_images/goods/02e/e8f/c4c/bb6/1210960_preview.jpg',
        isNew: true,
        isGoodPrice: false,
    },
    {
        id: '5',
        name: ' Road Bike',
        rating: 5,
        price: '$20.78',
        prevPrice: '60$',
        percent: '10%',
        imgUrl: 'https://fashionstore.ru/upload/iblock/fec/cnd6ejer33iunb8916g8b7gml9gwi5vp.jpg',
        isNew: true,
        isGoodPrice: false,
    },
    {
        id: '56',
        name: 'Exercise Bike',
        rating: 4.5,
        price: '$33.78',
        prevPrice: '60$',
        percent: '12%',
        imgUrl: 'https://jz9czo0xs6.ru.scalesta-cdn.com/_8MFOJ0DRsOHHfqMEhdgG6guPQs=/filters:format(webp):fill(fff)/https%3A%2F%2Fcomplexbar.ru%2Fimages%2Fdetailed%2F228%2FD681787F-2420-11EE-BC0D-005056921CC4.jpg',
        isNew: true,
        isGoodPrice: true,
    },

    {
        id: '536',
        name: 'MEROKEETY Women',
        rating: 4.5,
        price: '$33.78',
        prevPrice: '60$',
        percent: '33%',
        imgUrl: 'https://ir.ozone.ru/s3/multimedia-1-x/wc1000/7095331581.jpg',
        isNew: false,
        isGoodPrice: false,
    },
];
